Vagrant.configure("2") do |config|
  config.vm.box = "jakubknejzlik/xcode"
  config.vm.box_version = "0"

  config.vm.boot_timeout = 500


   config.vm.provider "virtualbox" do |v|
     v.linked_clone = false
     # Display the VirtualBox GUI when booting the machine
     v.gui = false
  
     # Customize the amount of memory on the VM:
     v.memory = 8192
     v.cpus = 4

     v.name = "ios-builder"
   end
  end
